import "@/app/globals.css";
import Header from "@/components/common/Header";
import type { Metadata } from "next";
import type React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};
const RootLayout: React.FC<RootLayoutProps> = (props) => (
  <html lang="en">
    <body className="bg-background">
      <Header />
      {props.children}
    </body>
  </html>
);

export default RootLayout;
